# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/kv260_fft_dma/kv260_fft_dma.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kv260_fft_dma || ORIG_REF_NAME==kv260_fft_dma} -quiet] -quiet

# IP: bd/kv260_fft_dma/ip/kv260_fft_dma_zynq_ultra_ps_e_0_1/kv260_fft_dma_zynq_ultra_ps_e_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kv260_fft_dma_zynq_ultra_ps_e_0_1 || ORIG_REF_NAME==kv260_fft_dma_zynq_ultra_ps_e_0_1} -quiet] -quiet

# IP: bd/kv260_fft_dma/ip/kv260_fft_dma_axi_dma_0_1/kv260_fft_dma_axi_dma_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kv260_fft_dma_axi_dma_0_1 || ORIG_REF_NAME==kv260_fft_dma_axi_dma_0_1} -quiet] -quiet

# IP: bd/kv260_fft_dma/ip/kv260_fft_dma_axi_interconnect_0_1/kv260_fft_dma_axi_interconnect_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kv260_fft_dma_axi_interconnect_0_1 || ORIG_REF_NAME==kv260_fft_dma_axi_interconnect_0_1} -quiet] -quiet

# IP: bd/kv260_fft_dma/ip/kv260_fft_dma_xbar_3/kv260_fft_dma_xbar_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kv260_fft_dma_xbar_3 || ORIG_REF_NAME==kv260_fft_dma_xbar_3} -quiet] -quiet

# IP: bd/kv260_fft_dma/ip/kv260_fft_dma_axi_interconnect_1_1/kv260_fft_dma_axi_interconnect_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kv260_fft_dma_axi_interconnect_1_1 || ORIG_REF_NAME==kv260_fft_dma_axi_interconnect_1_1} -quiet] -quiet

# IP: bd/kv260_fft_dma/ip/kv260_fft_dma_rst_ps8_0_99M_1/kv260_fft_dma_rst_ps8_0_99M_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kv260_fft_dma_rst_ps8_0_99M_1 || ORIG_REF_NAME==kv260_fft_dma_rst_ps8_0_99M_1} -quiet] -quiet

# IP: bd/kv260_fft_dma/ip/kv260_fft_dma_fft_dma_0_2/kv260_fft_dma_fft_dma_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kv260_fft_dma_fft_dma_0_2 || ORIG_REF_NAME==kv260_fft_dma_fft_dma_0_2} -quiet] -quiet

# IP: bd/kv260_fft_dma/ip/kv260_fft_dma_auto_pc_0/kv260_fft_dma_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kv260_fft_dma_auto_pc_0 || ORIG_REF_NAME==kv260_fft_dma_auto_pc_0} -quiet] -quiet

# XDC: d:/vivado-projekty/sdup_fft/parallel_dma_compliant/kv260_fft_dma/kv260_fft_dma.gen/sources_1/bd/kv260_fft_dma/kv260_fft_dma_ooc.xdc
