# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/vivado-projekty/sdup_fft/parallel_dma_compliant/kv260_fft_dma/kv260_fft_dma.srcs/sources_1/bd/kv260_fft_dma/ip/kv260_fft_dma_zynq_ultra_ps_e_0_1/kv260_fft_dma_zynq_ultra_ps_e_0_1.xci
# IP: The module: 'kv260_fft_dma_zynq_ultra_ps_e_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/vivado-projekty/sdup_fft/parallel_dma_compliant/kv260_fft_dma/kv260_fft_dma.gen/sources_1/bd/kv260_fft_dma/ip/kv260_fft_dma_zynq_ultra_ps_e_0_1/kv260_fft_dma_zynq_ultra_ps_e_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'kv260_fft_dma_zynq_ultra_ps_e_0_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/vivado-projekty/sdup_fft/parallel_dma_compliant/kv260_fft_dma/kv260_fft_dma.gen/sources_1/bd/kv260_fft_dma/ip/kv260_fft_dma_zynq_ultra_ps_e_0_1/kv260_fft_dma_zynq_ultra_ps_e_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'kv260_fft_dma_zynq_ultra_ps_e_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: d:/vivado-projekty/sdup_fft/parallel_dma_compliant/kv260_fft_dma/kv260_fft_dma.srcs/sources_1/bd/kv260_fft_dma/ip/kv260_fft_dma_zynq_ultra_ps_e_0_1/kv260_fft_dma_zynq_ultra_ps_e_0_1.xci
# IP: The module: 'kv260_fft_dma_zynq_ultra_ps_e_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/vivado-projekty/sdup_fft/parallel_dma_compliant/kv260_fft_dma/kv260_fft_dma.gen/sources_1/bd/kv260_fft_dma/ip/kv260_fft_dma_zynq_ultra_ps_e_0_1/kv260_fft_dma_zynq_ultra_ps_e_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'kv260_fft_dma_zynq_ultra_ps_e_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/vivado-projekty/sdup_fft/parallel_dma_compliant/kv260_fft_dma/kv260_fft_dma.gen/sources_1/bd/kv260_fft_dma/ip/kv260_fft_dma_zynq_ultra_ps_e_0_1/kv260_fft_dma_zynq_ultra_ps_e_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'kv260_fft_dma_zynq_ultra_ps_e_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
