# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/fft_seq/fft_seq.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fft_seq || ORIG_REF_NAME==fft_seq} -quiet] -quiet

# IP: bd/fft_seq/ip/fft_seq_fft_seq_ip_0_0/fft_seq_fft_seq_ip_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fft_seq_fft_seq_ip_0_0 || ORIG_REF_NAME==fft_seq_fft_seq_ip_0_0} -quiet] -quiet

# IP: bd/fft_seq/ip/fft_seq_zynq_ultra_ps_e_0_0/fft_seq_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fft_seq_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==fft_seq_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/fft_seq/ip/fft_seq_xbar_0/fft_seq_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fft_seq_xbar_0 || ORIG_REF_NAME==fft_seq_xbar_0} -quiet] -quiet

# IP: bd/fft_seq/ip/fft_seq_ps8_0_axi_periph_0/fft_seq_ps8_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fft_seq_ps8_0_axi_periph_0 || ORIG_REF_NAME==fft_seq_ps8_0_axi_periph_0} -quiet] -quiet

# IP: bd/fft_seq/ip/fft_seq_rst_ps8_0_99M_0/fft_seq_rst_ps8_0_99M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fft_seq_rst_ps8_0_99M_0 || ORIG_REF_NAME==fft_seq_rst_ps8_0_99M_0} -quiet] -quiet

# IP: bd/fft_seq/ip/fft_seq_auto_ds_0/fft_seq_auto_ds_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fft_seq_auto_ds_0 || ORIG_REF_NAME==fft_seq_auto_ds_0} -quiet] -quiet

# IP: bd/fft_seq/ip/fft_seq_auto_pc_0/fft_seq_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fft_seq_auto_pc_0 || ORIG_REF_NAME==fft_seq_auto_pc_0} -quiet] -quiet

# IP: bd/fft_seq/ip/fft_seq_auto_ds_1/fft_seq_auto_ds_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fft_seq_auto_ds_1 || ORIG_REF_NAME==fft_seq_auto_ds_1} -quiet] -quiet

# IP: bd/fft_seq/ip/fft_seq_auto_pc_1/fft_seq_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fft_seq_auto_pc_1 || ORIG_REF_NAME==fft_seq_auto_pc_1} -quiet] -quiet

# XDC: c:/Users/macie/Desktop/SDUP/Sekwencyjny_1_motyl/fft_seq/fft_seq.gen/sources_1/bd/fft_seq/fft_seq_ooc.xdc
