# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/fft_parallel/fft_parallel.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fft_parallel || ORIG_REF_NAME==fft_parallel} -quiet] -quiet

# IP: bd/fft_parallel/ip/fft_parallel_fft_parallel_ip_0_0/fft_parallel_fft_parallel_ip_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fft_parallel_fft_parallel_ip_0_0 || ORIG_REF_NAME==fft_parallel_fft_parallel_ip_0_0} -quiet] -quiet

# IP: bd/fft_parallel/ip/fft_parallel_zynq_ultra_ps_e_0_0/fft_parallel_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fft_parallel_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==fft_parallel_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/fft_parallel/ip/fft_parallel_ps8_0_axi_periph_0/fft_parallel_ps8_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fft_parallel_ps8_0_axi_periph_0 || ORIG_REF_NAME==fft_parallel_ps8_0_axi_periph_0} -quiet] -quiet

# IP: bd/fft_parallel/ip/fft_parallel_rst_ps8_0_99M_0/fft_parallel_rst_ps8_0_99M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fft_parallel_rst_ps8_0_99M_0 || ORIG_REF_NAME==fft_parallel_rst_ps8_0_99M_0} -quiet] -quiet

# IP: bd/fft_parallel/ip/fft_parallel_xbar_0/fft_parallel_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fft_parallel_xbar_0 || ORIG_REF_NAME==fft_parallel_xbar_0} -quiet] -quiet

# IP: bd/fft_parallel/ip/fft_parallel_auto_ds_0/fft_parallel_auto_ds_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fft_parallel_auto_ds_0 || ORIG_REF_NAME==fft_parallel_auto_ds_0} -quiet] -quiet

# IP: bd/fft_parallel/ip/fft_parallel_auto_pc_0/fft_parallel_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fft_parallel_auto_pc_0 || ORIG_REF_NAME==fft_parallel_auto_pc_0} -quiet] -quiet

# IP: bd/fft_parallel/ip/fft_parallel_auto_ds_1/fft_parallel_auto_ds_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fft_parallel_auto_ds_1 || ORIG_REF_NAME==fft_parallel_auto_ds_1} -quiet] -quiet

# IP: bd/fft_parallel/ip/fft_parallel_auto_pc_1/fft_parallel_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fft_parallel_auto_pc_1 || ORIG_REF_NAME==fft_parallel_auto_pc_1} -quiet] -quiet

# XDC: c:/Users/macie/Desktop/SDUP/fft_parallel/fft_parallel.gen/sources_1/bd/fft_parallel/fft_parallel_ooc.xdc
