# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/macie/Desktop/SDUP/Sekwencyjny_1_motyl/fft_seq/fft_seq.srcs/sources_1/bd/fft_seq/ip/fft_seq_zynq_ultra_ps_e_0_0/fft_seq_zynq_ultra_ps_e_0_0.xci
# IP: The module: 'fft_seq_zynq_ultra_ps_e_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/macie/Desktop/SDUP/Sekwencyjny_1_motyl/fft_seq/fft_seq.gen/sources_1/bd/fft_seq/ip/fft_seq_zynq_ultra_ps_e_0_0/fft_seq_zynq_ultra_ps_e_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fft_seq_zynq_ultra_ps_e_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/macie/Desktop/SDUP/Sekwencyjny_1_motyl/fft_seq/fft_seq.gen/sources_1/bd/fft_seq/ip/fft_seq_zynq_ultra_ps_e_0_0/fft_seq_zynq_ultra_ps_e_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'fft_seq_zynq_ultra_ps_e_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/macie/Desktop/SDUP/Sekwencyjny_1_motyl/fft_seq/fft_seq.srcs/sources_1/bd/fft_seq/ip/fft_seq_zynq_ultra_ps_e_0_0/fft_seq_zynq_ultra_ps_e_0_0.xci
# IP: The module: 'fft_seq_zynq_ultra_ps_e_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/macie/Desktop/SDUP/Sekwencyjny_1_motyl/fft_seq/fft_seq.gen/sources_1/bd/fft_seq/ip/fft_seq_zynq_ultra_ps_e_0_0/fft_seq_zynq_ultra_ps_e_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fft_seq_zynq_ultra_ps_e_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/macie/Desktop/SDUP/Sekwencyjny_1_motyl/fft_seq/fft_seq.gen/sources_1/bd/fft_seq/ip/fft_seq_zynq_ultra_ps_e_0_0/fft_seq_zynq_ultra_ps_e_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'fft_seq_zynq_ultra_ps_e_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
